version: '2'
catalog:
  name: "myservice"
  version: “0.1"
  description: "Package example to show private repo"
  questions:
    - variable: "PUBLISH_PORT"
      label: "Publish port"
      description: |
        Select port to publish service
      required: true
      default: "8080"
      type: int
services:
  test:
    scale: 2
    retain_ip: true
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ''
        priority: 1
        protocol: http
        service: test
        source_port: 8080
        target_port: 8080
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000